version: '3'
services:
    influxsrv:
        image: hyperpilot/influx:1.2.2
        ports:
            - "8083:8083"
            - "8086:8086"
        environment:
            - ADMIN_USER=root
            - INFLUXDB_INIT_PWD=default
            - PRE_CREATE_DB=snap

    snap:
        image: average-counter-processor
        links:
            - influxsrv:influxsrv
